"""Kumpulan doa harian. Arab disimpan apa adanya,
dirangkai ulang saat ditampilkan (arabic_reshaper + bidi)."""

DOA = [
    {"judul": "Doa Sebelum Makan",
     "arab": "اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ",
     "latin": "Allahumma barik lana fima razaktana wa qina 'adzaban nar",
     "arti": "Ya Allah, berkahilah rezeki yang Engkau berikan kepada kami, dan peliharalah kami dari azab neraka."},
    {"judul": "Doa Sesudah Makan",
     "arab": "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
     "latin": "Alhamdulillahil ladzi ath'amana wa saqana wa ja'alana muslimin",
     "arti": "Segala puji bagi Allah yang telah memberi kami makan dan minum, serta menjadikan kami muslim."},
    {"judul": "Doa Sebelum Tidur",
     "arab": "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
     "latin": "Bismika Allahumma amutu wa ahya",
     "arti": "Dengan nama-Mu ya Allah aku mati dan aku hidup."},
    {"judul": "Doa Bangun Tidur",
     "arab": "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
     "latin": "Alhamdulillahil ladzi ahyana ba'da ma amatana wa ilaihin nusyur",
     "arti": "Segala puji bagi Allah yang menghidupkan kami setelah mematikan kami, dan kepada-Nya kami dikembalikan."},
    {"judul": "Doa Masuk Kamar Mandi",
     "arab": "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
     "latin": "Allahumma inni a'udzu bika minal khubutsi wal khabaits",
     "arti": "Ya Allah, aku berlindung kepada-Mu dari setan laki-laki dan setan perempuan."},
    {"judul": "Doa Keluar Kamar Mandi",
     "arab": "غُفْرَانَكَ",
     "latin": "Gufranak",
     "arti": "Aku memohon ampunan-Mu."},
    {"judul": "Doa Keluar Rumah",
     "arab": "بِسْمِ اللهِ، تَوَكَّلْتُ عَلَى اللهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ",
     "latin": "Bismillahi, tawakkaltu 'alallah, wa la haula wa la quwwata illa billah",
     "arti": "Dengan nama Allah, aku bertawakal kepada Allah, tiada daya dan kekuatan kecuali dengan pertolongan Allah."},
    {"judul": "Doa Naik Kendaraan",
     "arab": "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
     "latin": "Subhanal ladzi sakhkhara lana hadza wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun",
     "arti": "Maha suci Allah yang telah menundukkan (kendaraan) ini bagi kami, padahal kami tidak mampu menguasainya. Dan sungguh hanya kepada Tuhan kami kami akan kembali."},
    {"judul": "Doa Sebelum Belajar",
     "arab": "رَبِّ زِدْنِي عِلْمًا",
     "latin": "Rabbi zidni 'ilma",
     "arti": "Ya Tuhanku, tambahkanlah ilmu kepadaku."},
    {"judul": "Doa untuk Kedua Orang Tua",
     "arab": "رَبِّ اغْفِرْ لَهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
     "latin": "Rabbighfir lahuma kama rabbayani shagira",
     "arti": "Ya Tuhanku, ampunilah keduanya sebagaimana mereka menyayangiku di masa kecil."},
]