"""Kumpulan doa harian IbadahKu.

Koleksi dibuat ringkas supaya nyaman dibaca dari layar HP. Teks Arab
dibiarkan sebagai teks sumber dan dirapikan saat ditampilkan oleh aplikasi.
"""

DOA = [
    {"judul": "Doa Sebelum Makan", "arab": "اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ", "latin": "Allahumma barik lana fima razaqtana wa qina 'adzaban nar", "arti": "Ya Allah, berkahilah rezeki yang Engkau berikan kepada kami dan lindungilah kami dari azab neraka."},
    {"judul": "Doa Sesudah Makan", "arab": "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ", "latin": "Alhamdulillahil ladzi ath'amana wa saqana wa ja'alana muslimin", "arti": "Segala puji bagi Allah yang telah memberi kami makan dan minum serta menjadikan kami muslim."},
    {"judul": "Doa Sebelum Tidur", "arab": "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", "latin": "Bismika Allahumma amutu wa ahya", "arti": "Dengan nama-Mu ya Allah, aku mati dan aku hidup."},
    {"judul": "Doa Bangun Tidur", "arab": "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ", "latin": "Alhamdulillahil ladzi ahyana ba'da ma amatana wa ilaihin nusyur", "arti": "Segala puji bagi Allah yang menghidupkan kami setelah mematikan kami dan kepada-Nya kami kembali."},
    {"judul": "Doa Masuk Kamar Mandi", "arab": "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ", "latin": "Allahumma inni a'udzu bika minal khubutsi wal khabaits", "arti": "Ya Allah, aku berlindung kepada-Mu dari setan laki-laki dan setan perempuan."},
    {"judul": "Doa Keluar Kamar Mandi", "arab": "غُفْرَانَكَ", "latin": "Ghufranak", "arti": "Aku memohon ampunan-Mu."},
    {"judul": "Doa Keluar Rumah", "arab": "بِسْمِ اللهِ، تَوَكَّلْتُ عَلَى اللهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ", "latin": "Bismillahi, tawakkaltu 'alallah, wa la haula wa la quwwata illa billah", "arti": "Dengan nama Allah, aku bertawakal kepada Allah. Tiada daya dan kekuatan kecuali dengan pertolongan Allah."},
    {"judul": "Doa Masuk Rumah", "arab": "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا", "latin": "Bismillahi walajna wa bismillahi kharajna wa 'alallahi rabbina tawakkalna", "arti": "Dengan nama Allah kami masuk, dengan nama Allah kami keluar, dan kepada Allah Tuhan kami bertawakal."},
    {"judul": "Doa Naik Kendaraan", "arab": "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ", "latin": "Subhanal ladzi sakhkhara lana hadza wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun", "arti": "Maha suci Allah yang telah menundukkan kendaraan ini bagi kami, padahal kami tidak mampu menguasainya. Kepada Tuhan kami akan kembali."},
    {"judul": "Doa Sebelum Belajar", "arab": "رَبِّ زِدْنِي عِلْمًا", "latin": "Rabbi zidni 'ilma", "arti": "Ya Tuhanku, tambahkanlah ilmu kepadaku."},
    {"judul": "Doa Memohon Kemudahan", "arab": "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي", "latin": "Rabbishrah li shadri wa yassir li amri", "arti": "Ya Tuhanku, lapangkanlah dadaku dan mudahkanlah urusanku."},
    {"judul": "Doa Memohon Ilmu yang Bermanfaat", "arab": "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي", "latin": "Allahummanfa'ni bima 'allamtani wa 'allimni ma yanfa'uni", "arti": "Ya Allah, berilah manfaat kepadaku dari ilmu yang Engkau ajarkan dan ajarkanlah kepadaku ilmu yang bermanfaat."},
    {"judul": "Doa untuk Kedua Orang Tua", "arab": "رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", "latin": "Rabbighfir li wa liwalidayya warhamhuma kama rabbayani shaghira", "arti": "Ya Tuhanku, ampunilah aku dan kedua orang tuaku serta sayangilah mereka sebagaimana mereka menyayangiku ketika kecil."},
    {"judul": "Doa Memohon Ampunan", "arab": "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ", "latin": "Rabbighfir li wa tub 'alayya innaka antat tawwabur rahim", "arti": "Ya Tuhanku, ampunilah aku dan terimalah tobatku. Sungguh Engkau Maha Penerima Tobat, Maha Penyayang."},
    {"judul": "Doa Kebaikan Dunia dan Akhirat", "arab": "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", "latin": "Rabbana atina fid dunya hasanah wa fil akhirati hasanah wa qina 'adzaban nar", "arti": "Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat serta lindungilah kami dari azab neraka."},
    {"judul": "Doa Memohon Keteguhan Hati", "arab": "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا", "latin": "Rabbana la tuzigh qulubana ba'da idz hadaitana", "arti": "Ya Tuhan kami, janganlah Engkau palingkan hati kami setelah Engkau memberi petunjuk kepada kami."},
    {"judul": "Doa Perlindungan", "arab": "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", "latin": "A'udzu bikalimatillahit tammati min syarri ma khalaq", "arti": "Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari kejahatan makhluk yang Dia ciptakan."},
    {"judul": "Doa Saat Hujan", "arab": "اللَّهُمَّ صَيِّبًا نَافِعًا", "latin": "Allahumma shayyiban nafi'an", "arti": "Ya Allah, jadikanlah hujan ini hujan yang bermanfaat."},
    {"judul": "Doa Setelah Hujan", "arab": "مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ", "latin": "Muthirna bifadhlillahi wa rahmatih", "arti": "Kami diberi hujan karena karunia Allah dan rahmat-Nya."},
    {"judul": "Doa Saat Mendapat Kebaikan", "arab": "الْحَمْدُ لِلَّهِ عَلَى كُلِّ حَالٍ", "latin": "Alhamdulillahi 'ala kulli hal", "arti": "Segala puji bagi Allah dalam setiap keadaan."},
    {"judul": "Doa Mohon Kesehatan", "arab": "اللَّهُمَّ عَافِنِي فِي بَدَنِي وَعَافِنِي فِي سَمْعِي وَعَافِنِي فِي بَصَرِي", "latin": "Allahumma 'afini fi badani wa 'afini fi sam'i wa 'afini fi bashari", "arti": "Ya Allah, berikanlah kesehatan pada tubuhku, pendengaranku, dan penglihatanku."},
    {"judul": "Doa Memohon Rezeki Halal", "arab": "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ", "latin": "Allahummakfini bihalalika 'an haramika wa aghnini bifadhlika 'amman siwak", "arti": "Ya Allah, cukupkanlah aku dengan yang halal sehingga aku terhindar dari yang haram dan cukupkan aku dengan karunia-Mu dari selain-Mu."},
    {"judul": "Doa Saat Sedih", "arab": "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ", "latin": "Allahumma inni a'udzu bika minal hammi wal hazan", "arti": "Ya Allah, aku berlindung kepada-Mu dari kegelisahan dan kesedihan."},
    {"judul": "Doa Sebelum Tidur Singkat", "arab": "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ", "latin": "Allahumma qini 'adzabaka yauma tab'atsu 'ibadak", "arti": "Ya Allah, lindungilah aku dari azab-Mu pada hari Engkau membangkitkan hamba-hamba-Mu."},
    {"judul": "Doa Memohon Hati yang Bersih", "arab": "اللَّهُمَّ طَهِّرْ قَلْبِي وَاغْفِرْ ذَنْبِي", "latin": "Allahumma thahhir qalbi waghfir dzanbi", "arti": "Ya Allah, bersihkanlah hatiku dan ampunilah dosaku."},
]
